SELECT CASE TRIM(Location) WHEN "" THEN 'NA' ELSE TRIM(Location) END Location, 
       COUNT(*) CNT
FROM JOBOPPORTUNITY 
GROUP BY CASE TRIM(Location) WHEN "" THEN 'NA' ELSE TRIM(Location) END
ORDER BY CASE TRIM(Location) WHEN "" THEN 'NA' ELSE TRIM(Location) END
;

SELECT CASE TRIM(Location) WHEN "" THEN 'NA' ELSE TRIM(Location) END Location, 
       COUNT(*) CNT, COUNT(*)*100/(SELECT COUNT(*) FROM JOBOPPORTUNITY) AV
FROM JOBOPPORTUNITY 
GROUP BY CASE TRIM(Location) WHEN "" THEN 'NA' ELSE TRIM(Location) END
ORDER BY CASE TRIM(Location) WHEN "" THEN 'NA' ELSE TRIM(Location) END
;
